image: node:latest

stages:
  - test
  - build
  - sonar
  - deploy

variables:
  APP_NAME: projet_co2
  SONAR_HOST_URL: "https://sonar.info.univ-lyon1.fr/"
  SONAR_PROJECT_KEY: "co2_project"

before_script:
  # Configuration de SSH
  - mkdir -p ~/.ssh
  - echo "$SSH_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 192.168.75.79 >> ~/.ssh/known_hosts

# Étape de test (uniquement pour la branche main)
test:
  stage: test
  script:
    - cd back
    - npm install
    # - npm test
  only:
    - main
  allow_failure: true

# Étape de build (installation des dépendances)
build:
  stage: build
  script:
    - cd back
    - npm install
    - echo "Vérification du projet backend..."
  artifacts:
    paths:
      - back/package.json
      - back/package-lock.json
    expire_in: 1 day
  only:
    - main
    - Back

# Analyse SonarQube (uniquement pour main)
sonar:
  stage: sonar
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_LOGIN: $SONAR_TOKEN
  script:
    - sonar-scanner
  only:
    - main

# Déploiement du back (main + Back)
deploy-back:
  stage: deploy
  script:
    - echo "Déploiement du backend sur la VM"
    - chmod 600 ~/.ssh/id_rsa
    # Copier uniquement le dossier "back"
    - scp -i ~/.ssh/id_rsa -r back gitlabci@192.168.75.79:/opt/express/
    - ssh -i ~/.ssh/id_rsa gitlabci@192.168.75.79 "
        cd /opt/express/back &&
        npm install &&
        pm2 restart $APP_NAME || pm2 start server.js --name $APP_NAME &&
        pm2 save &&
        pm2 status"
  only:
    - main
    - Back

# Déploiement du front (main + Front)
deploy-front:
  stage: deploy
  script:
    - echo "Déploiement du frontend sur la VM"
    - chmod 600 ~/.ssh/id_rsa
    # Copier les fichiers du dossier "end"
    - scp -i ~/.ssh/id_rsa -r end/* gitlabci@192.168.75.79:/usr/share/nginx/html/
  only:
    - main
    - Front

  environment:
    name: production
    url: http://192.168.75.79
