"""feat(emission co2): now save in db

Revision ID: c4df04a4cd42
Revises: 39f231ac10fa
Create Date: 2025-05-18 22:47:37.741525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4df04a4cd42'
down_revision: Union[str, None] = '39f231ac10fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission',
    sa.Column('transport_mode', sa.String(), nullable=False),
    sa.Column('emission_per_km', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('transport_mode')
    )
    # ### end Alembic commands ###
    
    emissions_data = {
        "driving-car": 150,
        "driving-hgv": 1000,
        "cycling-regular": 0,
        "cycling-road": 0,
        "cycling-mountain": 0,
        "cycling-electric": 15,
        "foot-walking": 0,
        "foot-hiking": 0,
        "wheelchair": 0
    }

    for mode, emission in emissions_data.items():
        op.execute(
            sa.text(
                "INSERT INTO emission (transport_mode, emission_per_km) VALUES (:mode, :emission)"
            ).bindparams(mode=mode, emission=emission)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emission')
    # ### end Alembic commands ###
